### ISSUE TITLE
Can't compile on OS X 10.8.4

### ISSUE THREAD

**Issue by pymssql-issue-migrator** [pymssql/pymssql#129]
_From [markaric...@gmail.com](https://code.google.com/u/115110308859529655232/) on September 01, 2013 16:05:54_

I got latest (pymssql-2.0.0b1-dev-20130403).

Here's the fatal error:

_mssql.c:257:10: fatal error: 'sqlfront.h' file not found

Full trace:

mark@macpro:pymssql-2.0.0b1-dev-20130403# python setup.py install
Compiling module Cython.Plex.Scanners ...
Compiling module Cython.Plex.Actions ...
Compiling module Cython.Compiler.Lexicon ...
Compiling module Cython.Compiler.Scanning ...
Compiling module Cython.Compiler.Parsing ...
Compiling module Cython.Compiler.Visitor ...
Compiling module Cython.Compiler.FlowControl ...
Compiling module Cython.Compiler.Code ...
Compiling module Cython.Runtime.refnanny ...
warning: no files found matching '_.pyx' under directory 'Cython/Debugger/Tests'
warning: no files found matching '_.pxd' under directory 'Cython/Debugger/Tests'
warning: no files found matching '_.h' under directory 'Cython/Debugger/Tests'
warning: no files found matching '_.pxd' under directory 'Cython/Utility'
/var/folders/hn/40d_ql_d21n4kg32cc0sd5p40000gn/T/easy_install-M9_3dW/Cython-0.19.1/Cython/Compiler/Code.c:50081:19: warning: expression result unused [-Wunused-value]
    PyObject_INIT(o, t);
                  ^
/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/include/python2.7/objimpl.h:164:69: note: expanded from macro 'PyObject_INIT'
    ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
                                                                    ^
1 warning generated.

Installed /Users/mark/pymssql-2.0.0b1-dev-20130403/Cython-0.19.1-py2.7-macosx-10.8-x86_64.egg
creating var
creating var/folders
creating var/folders/hn
creating var/folders/hn/40d_ql_d21n4kg32cc0sd5p40000gn
creating var/folders/hn/40d_ql_d21n4kg32cc0sd5p40000gn/T
cc -arch x86_64 -c /var/folders/hn/40d_ql_d21n4kg32cc0sd5p40000gn/T/clock_gettimeOd2mcR.c -o var/folders/hn/40d_ql_d21n4kg32cc0sd5p40000gn/T/clock_gettimeOd2mcR.o
/var/folders/hn/40d_ql_d21n4kg32cc0sd5p40000gn/T/clock_gettimeOd2mcR.c:1:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
main (int argc, char **argv) {
^~~~
/var/folders/hn/40d_ql_d21n4kg32cc0sd5p40000gn/T/clock_gettimeOd2mcR.c:2:5: warning: implicit declaration of function 'clock_gettime' is invalid in C99
      [-Wimplicit-function-declaration]
    clock_gettime();
    ^
2 warnings generated.
cc -arch x86_64 var/folders/hn/40d_ql_d21n4kg32cc0sd5p40000gn/T/clock_gettimeOd2mcR.o -lrt -o a.out
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
running install
running bdist_egg
running egg_info
writing pymssql.egg-info/PKG-INFO
writing top-level names to pymssql.egg-info/top_level.txt
writing dependency_links to pymssql.egg-info/dependency_links.txt
reading manifest file 'pymssql.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'win32/freetds.zip'
writing manifest file 'pymssql.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.8-x86_64/egg
running install_lib
running build_ext
skipping '_mssql.c' Cython extension (up-to-date)
building '_mssql' extension
creating build
creating build/temp.macosx-10.8-x86_64-2.7
cc -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -I/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _mssql.c -o build/temp.macosx-10.8-x86_64-2.7/_mssql.o -Wno-parentheses-equality -DMSDBLIB
_mssql.c:257:10: fatal error: 'sqlfront.h' file not found
# include "sqlfront.h"

```
     ^
```

1 error generated.
error: command 'cc' failed with exit status 1

_Original issue: http://code.google.com/p/pymssql/issues/detail?id=125_

**Comment by dkalaria** [comment]
On Mac

- brew install freetds@0.91
- brew link --force freetds@0.91
- pip install pymssql

**Comment by cliffwildman** [comment]
@dkalaria your comment just saved me a few hours. Thanks!

**Comment by cuishuang** [comment]
brew unlink freetds
brew install freetds@0.91
brew link --force freetds@0.91
sudo pip install pymssql

**Comment by erg** [comment]
Still having this problem on macOS, none of these solutions worked anymore except this:

``sudo pip3 install git+https://github.com/pymssql/pymssql.git``

**Comment by tenadolanter** [comment]
brew unlink freetds
brew install freetds@0.91
brew link --force freetds@0.91 // if error,run `  brew link --overwrite freetds@0.91`
sudo pip install pymssql

**Comment by Ctrlsman** [comment]
download: http://mirrors.ibiblio.org/freetds/stable/freetds-0.91.tar.gz
./configure --enable-msdblib
make && make install

**Comment by sscarduzio** [comment]
The only thing that worked is [this](https://stackoverflow.com/a/70333974/1094616) on apple M1

1. brew install freetds
2. brew install openssl
3. export LDFLAGS="-L/opt/homebrew/Cellar/freetds/1.3.3/lib -L/opt/homebrew/Cellar/openssl@1.1/1.1.1l_1/lib"
4. export CFLAGS="-I/opt/homebrew/Cellar/freetds/1.3.3/include" 
5. pip install pymssql

(change the versions to your systems libraries versions)

**Comment by max-pfeiffer** [comment]
@sscarduzio Thanks for the hint. I am using Mac Ports, so you need to tweak that flags for the directories a bit:

```
export CFLAGS="-I/opt/local/include/freetds"
export LDFLAGS="-L/opt/local/lib/"
pip install pymssql==2.2.8 
```
